/* 
   SANE EPSON backend
   Copyright (C) 2001, 2008  SEIKO EPSON CORPORATION

   Date         Author      Reason
   06/01/2001   N.Sasaki    New

   This file is part of the `iscan' program.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

   As a special exception, the copyright holders give permission
   to link the code of this program with the esmod library and
   distribute linked combinations including the two.  You must obey
   the GNU General Public License in all respects for all of the
   code used other then esmod.
*/

// scan button
const char * scan_xpm[] = {
"36 28 257 2",
"  	c None",
". 	c #0C0C0C",
"+ 	c #252426",
"@ 	c #252526",
"# 	c #262527",
"$ 	c #262628",
"% 	c #292929",
"& 	c #2C2B2D",
"* 	c #2E2E30",
"= 	c #402810",
"- 	c #373638",
"; 	c #373737",
"> 	c #3C3B3E",
", 	c #3D3C3E",
"' 	c #403F42",
") 	c #414042",
"! 	c #424043",
"~ 	c #424144",
"{ 	c #444444",
"] 	c #49484B",
"^ 	c #4A494C",
"/ 	c #4E4C50",
"( 	c #525154",
"_ 	c #58565B",
": 	c #5A585C",
"< 	c #5A5A5A",
"[ 	c #5B595D",
"} 	c #5C5A5E",
"| 	c #5D5B5F",
"1 	c #5E5C60",
"2 	c #5E5E5E",
"3 	c #5F5D61",
"4 	c #5F5F5F",
"5 	c #636166",
"6 	c #656367",
"7 	c #656368",
"8 	c #656468",
"9 	c #686868",
"0 	c #69676C",
"a 	c #6A6A6A",
"b 	c #6C6A6E",
"c 	c #6E6C71",
"d 	c #408080",
"e 	c #717171",
"f 	c #727075",
"g 	c #737177",
"h 	c #737373",
"i 	c #747278",
"j 	c #757575",
"k 	c #767676",
"l 	c #77757A",
"m 	c #7A777D",
"n 	c #7A787E",
"o 	c #7B7B7B",
"p 	c #7C7A80",
"q 	c #7D7B80",
"r 	c #7F7D82",
"s 	c #7F7F7F",
"t 	c #817E84",
"u 	c #808080",
"v 	c #817F85",
"w 	c #827F85",
"x 	c #818181",
"y 	c #828086",
"z 	c #848288",
"A 	c #E63A3A",
"B 	c #89868D",
"C 	c #89878D",
"D 	c None",
"E 	c #8A888E",
"F 	c #8B898F",
"G 	c #8C8990",
"H 	c #8D8A91",
"I 	c #8D8B91",
"J 	c #8E8B91",
"K 	c #8F8D93",
"L 	c #908E94",
"M 	c #F63E3E",
"N 	c #928F96",
"O 	c #939097",
"P 	c #3E9AF6",
"Q 	c #949198",
"R 	c #959299",
"S 	c #949494",
"T 	c #96949A",
"U 	c #FF4040",
"V 	c #97949B",
"W 	c #97959B",
"X 	c #809F9F",
"Y 	c #979797",
"Z 	c #40A0FF",
"` 	c #9A979E",
" .	c #999999",
"..	c #9B989F",
"+.	c #9C99A0",
"@.	c #9D9AA1",
"#.	c #9D9BA2",
"$.	c #9E9BA3",
"%.	c #A09DA4",
"&.	c #A29FA6",
"*.	c #A5A2AA",
"=.	c #A6A3AB",
"-.	c #A8A5AC",
";.	c #AAA7AE",
">.	c #ABA7AF",
",.	c #60C0C0",
"'.	c #ABA8B0",
").	c #ACA9B1",
"!.	c #ADAAB2",
"~.	c #AEABB3",
"{.	c #B0ADB5",
"].	c #B1ADB5",
"^.	c #B0B0B0",
"/.	c #B2AEB6",
"(.	c #B2AFB7",
"_.	c #B3B0B8",
":.	c #B5B2BA",
"<.	c #B6B3BB",
"[.	c #B7B4BC",
"}.	c #B8B4BD",
"|.	c #B7B7B7",
"1.	c #B9B5BD",
"2.	c #B9B6BE",
"3.	c #BBB7BF",
"4.	c #BBB8C0",
"5.	c #BCB9C1",
"6.	c #BDBAC2",
"7.	c #FFA040",
"8.	c #BEBAC3",
"9.	c #BDBDBD",
"0.	c #BFBBC4",
"a.	c #C0BCC5",
"b.	c #C0BDC6",
"c.	c #C1BEC6",
"d.	c #C0C0C0",
"e.	c #C2BFC7",
"f.	c #C3C0C8",
"g.	c #C5C1CA",
"h.	c #90E63A",
"i.	c #C6C2CB",
"j.	c #C7C3CC",
"k.	c #C7C4CD",
"l.	c #C8C5CD",
"m.	c #C8C5CE",
"n.	c #C9C6CF",
"o.	c #CAC6CF",
"p.	c #CBC7D0",
"q.	c #CCC8D1",
"r.	c #CCCCCC",
"s.	c #CECAD3",
"t.	c #CECBD4",
"u.	c #CFCCD5",
"v.	c #D0CCD6",
"w.	c #D1CDD7",
"x.	c #D2CED8",
"y.	c #D3CFD8",
"z.	c #9AF63E",
"A.	c #D4D0DA",
"B.	c #D3D3D3",
"C.	c #D5D1DA",
"D.	c #D6D2DC",
"E.	c #D7D3DD",
"F.	c #D8D4DE",
"G.	c #D9D5DF",
"H.	c #DAD6E0",
"I.	c #A0FF40",
"J.	c #DBD7E1",
"K.	c #DCD8E1",
"L.	c #DCD8E2",
"M.	c #DDD9E3",
"N.	c #DEDAE4",
"O.	c #DFDBE5",
"P.	c #80FFFF",
"Q.	c #E3E3E3",
"R.	c #E6E6E6",
"S.	c #F6F6F6",
"T.	c #FCFCFC",
"U.	c #FFFFFF",
"V.	c #000000",
"W.	c #000000",
"X.	c #000000",
"Y.	c #000000",
"Z.	c #000000",
"`.	c #000000",
" +	c #000000",
".+	c #000000",
"++	c #000000",
"@+	c #000000",
"#+	c #000000",
"$+	c #000000",
"%+	c #000000",
"&+	c #000000",
"*+	c #000000",
"=+	c #000000",
"-+	c #000000",
";+	c #000000",
">+	c #000000",
",+	c #000000",
"'+	c #000000",
")+	c #000000",
"!+	c #000000",
"~+	c #000000",
"{+	c #000000",
"]+	c #000000",
"^+	c #000000",
"/+	c #000000",
"(+	c #000000",
"_+	c #000000",
":+	c #000000",
"<+	c #000000",
"[+	c #000000",
"}+	c #000000",
"|+	c #000000",
"1+	c #000000",
"2+	c #000000",
"3+	c #000000",
"4+	c #000000",
"5+	c #000000",
"6+	c #000000",
"7+	c #000000",
"8+	c #000000",
"9+	c #000000",
"0+	c #000000",
"a+	c #000000",
"b+	c #000000",
"c+	c #000000",
"d+	c #000000",
"e+	c #000000",
"f+	c #000000",
"g+	c #000000",
"h+	c #000000",
"i+	c #000000",
"j+	c #000000",
"k+	c #000000",
"l+	c #000000",
"m+	c #000000",
"n+	c #000000",
"o+	c #000000",
"p+	c #000000",
"q+	c #000000",
"r+	c #000000",
"s+	c #000000",
"t+	c #000000",
"u+	c #000000",
"v+	c #000000",
"w+	c #000000",
"x+	c #000000",
"y+	c #000000",
"z+	c #000000",
"A+	c #000000",
"B+	c #000000",
"C+	c #000000",
"D+	c #000000",
"E+	c #000000",
"F+	c #000000",
"G+	c #000000",
"H+	c #000000",
"D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D ",
"D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D ",
"D D D D D &.Q K N +.>.[.4.0.D D D D D D D D D D D D D D D D D D D D D D ",
"D D D D D  . . . . .n t C L +.>.[.D D D D D D D D D D D D D D D D D D D ",
"D D D D D !.r.d.d.d. . . . . .n t C J K N +.D D D D D D D D D D D D D D ",
"D D D D D D -.r.r.r.d.d.d.d.d. . . . . .u u u H *.D D D D D D D D D D D ",
"D D D D D D D D T y r.r.r.d.d.d.d.d.d.d.d.u u u u F *.D D D D D D D D D ",
"D D D D D D D D D _.#.t 6 r.r.r.d.d.d.d.d.d.d.u u u u F *.D D D D D D D ",
"D D D D D D D D D 5.*.E f } d.d.r.r.d.d.d.d.d.d.d.u u u u F =.D D D D D ",
"D D D D D D D D /.V l m d.d.d.d.u u r.u d.d.d.d.d.d.d.u u u u O }.D D D ",
"D D D D D D /...w 7 d.d.U.U.u { U.d d d u u u u u u d.d.d.u u u u D D D ",
"D D D D /...w 7 d.d.U.U.u u U.,.U.,.,.d d d d d d d { u { { { { { R D D ",
"D D /...w 7 d.d.U.U.u u U.U.U.,.U.,.,.,.,.d d d d d u u d.d.{ { u { !.D ",
"D ;.z 7 d.d.U.U.u X ,.,.U.U.U.,.U.,.,.,.,.,.,.d u u d.d.{ { u u u { +.D ",
"D T d.d.U.U.u u ,.,.,.,.U.U.U.,.U.,.,.,.,.,.d.u d.d.{ { u u u u u { O D ",
"D L d.d.d.U.U.U.u X ,.,.U.U.U.,.U.,.,.,.d.d.U.U.{ { u u u u u u u { R D ",
"D K d.U.U.d.d.U.U.U.u u U.U.U.,.U.,.d.d.U.U.{ { u u u u u u u u { t &.D ",
"D N d.U.U.U.U.d.d.U.U.U.u u U.,.d.d.U.U.{ { u u u u u u u u { { t D D D ",
"D $.d.U.u U.U.U.U.d.d.U.U.U.u u U.U.{ { u u u u u u u u { { p G D D D D ",
"D :.d.U.U.u U.U.U.U.U.d.d.U.U.U.{ { u u u u u u u u { { p G D D D D D D ",
"D D !.u u U.U.U.U.U.U.U.U.d.{ { u u u u u u u u { { p G D D D D D D D D ",
"D D D ~.H u u U.U.U.U.U.U.U.{ u u u u u u u { { p G $.D D D D D D D D D ",
"D D D D D =.E u u U.U.U.U.U.{ u u u u u { { p G $.D D D D D D D D D D D ",
"D D D D D D D =.E u u U.U.U.{ u u u { { p G $.D D D D D D D D D D D D D ",
"D D D D D D D D D =.E u u U.{ u { { p G D D D D D D D D D D D D D D D D ",
"D D D D D D D D D D D =.G u { { p G D D D D D D D D D D D D D D D D D D ",
"D D D D D D D D D D D D D !.#.W %.D D D D D D D D D D D D D D D D D D D ",
"D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D D "};

// preview button
const char * preview_xpm[] = {
"18 18 257 2",
"  	c None",
". 	c #0C0C0C",
"+ 	c #252426",
"@ 	c #252526",
"# 	c #262527",
"$ 	c #262628",
"% 	c #292929",
"& 	c #2C2B2D",
"* 	c #2E2E30",
"= 	c #402810",
"- 	c #373638",
"; 	c #373737",
"> 	c #3C3B3E",
", 	c #3D3C3E",
"' 	c #403F42",
") 	c #414042",
"! 	c #424043",
"~ 	c #424144",
"{ 	c #444444",
"] 	c #49484B",
"^ 	c #4A494C",
"/ 	c #4E4C50",
"( 	c #525154",
"_ 	c #58565B",
": 	c #5A585C",
"< 	c #5A5A5A",
"[ 	c #5B595D",
"} 	c #5C5A5E",
"| 	c #5D5B5F",
"1 	c #5E5C60",
"2 	c #5E5E5E",
"3 	c #5F5D61",
"4 	c #5F5F5F",
"5 	c #636166",
"6 	c #656367",
"7 	c #656368",
"8 	c #656468",
"9 	c #686868",
"0 	c #69676C",
"a 	c #6A6A6A",
"b 	c #6C6A6E",
"c 	c #6E6C71",
"d 	c #408080",
"e 	c #717171",
"f 	c #727075",
"g 	c #737177",
"h 	c #737373",
"i 	c #747278",
"j 	c #757575",
"k 	c #767676",
"l 	c #77757A",
"m 	c #7A777D",
"n 	c #7A787E",
"o 	c #7B7B7B",
"p 	c #7C7A80",
"q 	c #7D7B80",
"r 	c #7F7D82",
"s 	c #7F7F7F",
"t 	c #817E84",
"u 	c #808080",
"v 	c #817F85",
"w 	c #827F85",
"x 	c #818181",
"y 	c #828086",
"z 	c #848288",
"A 	c #E63A3A",
"B 	c #89868D",
"C 	c #89878D",
"D 	c None",
"E 	c #8A888E",
"F 	c #8B898F",
"G 	c #8C8990",
"H 	c #8D8A91",
"I 	c #8D8B91",
"J 	c #8E8B91",
"K 	c #8F8D93",
"L 	c #908E94",
"M 	c #F63E3E",
"N 	c #928F96",
"O 	c #939097",
"P 	c #3E9AF6",
"Q 	c #949198",
"R 	c #959299",
"S 	c #949494",
"T 	c #96949A",
"U 	c #FF4040",
"V 	c #97949B",
"W 	c #97959B",
"X 	c #809F9F",
"Y 	c #979797",
"Z 	c #40A0FF",
"` 	c #9A979E",
" .	c #999999",
"..	c #9B989F",
"+.	c #9C99A0",
"@.	c #9D9AA1",
"#.	c #9D9BA2",
"$.	c #9E9BA3",
"%.	c #A09DA4",
"&.	c #A29FA6",
"*.	c #A5A2AA",
"=.	c #A6A3AB",
"-.	c #A8A5AC",
";.	c #AAA7AE",
">.	c #ABA7AF",
",.	c #60C0C0",
"'.	c #ABA8B0",
").	c #ACA9B1",
"!.	c #ADAAB2",
"~.	c #AEABB3",
"{.	c #B0ADB5",
"].	c #B1ADB5",
"^.	c #B0B0B0",
"/.	c #B2AEB6",
"(.	c #B2AFB7",
"_.	c #B3B0B8",
":.	c #B5B2BA",
"<.	c #B6B3BB",
"[.	c #B7B4BC",
"}.	c #B8B4BD",
"|.	c #B7B7B7",
"1.	c #B9B5BD",
"2.	c #B9B6BE",
"3.	c #BBB7BF",
"4.	c #BBB8C0",
"5.	c #BCB9C1",
"6.	c #BDBAC2",
"7.	c #FFA040",
"8.	c #BEBAC3",
"9.	c #BDBDBD",
"0.	c #BFBBC4",
"a.	c #C0BCC5",
"b.	c #C0BDC6",
"c.	c #C1BEC6",
"d.	c #C0C0C0",
"e.	c #C2BFC7",
"f.	c #C3C0C8",
"g.	c #C5C1CA",
"h.	c #90E63A",
"i.	c #C6C2CB",
"j.	c #C7C3CC",
"k.	c #C7C4CD",
"l.	c #C8C5CD",
"m.	c #C8C5CE",
"n.	c #C9C6CF",
"o.	c #CAC6CF",
"p.	c #CBC7D0",
"q.	c #CCC8D1",
"r.	c #CCCCCC",
"s.	c #CECAD3",
"t.	c #CECBD4",
"u.	c #CFCCD5",
"v.	c #D0CCD6",
"w.	c #D1CDD7",
"x.	c #D2CED8",
"y.	c #D3CFD8",
"z.	c #9AF63E",
"A.	c #D4D0DA",
"B.	c #D3D3D3",
"C.	c #D5D1DA",
"D.	c #D6D2DC",
"E.	c #D7D3DD",
"F.	c #D8D4DE",
"G.	c #D9D5DF",
"H.	c #DAD6E0",
"I.	c #A0FF40",
"J.	c #DBD7E1",
"K.	c #DCD8E1",
"L.	c #DCD8E2",
"M.	c #DDD9E3",
"N.	c #DEDAE4",
"O.	c #DFDBE5",
"P.	c #80FFFF",
"Q.	c #E3E3E3",
"R.	c #E6E6E6",
"S.	c #F6F6F6",
"T.	c #FCFCFC",
"U.	c #FFFFFF",
"V.	c #000000",
"W.	c #000000",
"X.	c #000000",
"Y.	c #000000",
"Z.	c #000000",
"`.	c #000000",
" +	c #000000",
".+	c #000000",
"++	c #000000",
"@+	c #000000",
"#+	c #000000",
"$+	c #000000",
"%+	c #000000",
"&+	c #000000",
"*+	c #000000",
"=+	c #000000",
"-+	c #000000",
";+	c #000000",
">+	c #000000",
",+	c #000000",
"'+	c #000000",
")+	c #000000",
"!+	c #000000",
"~+	c #000000",
"{+	c #000000",
"]+	c #000000",
"^+	c #000000",
"/+	c #000000",
"(+	c #000000",
"_+	c #000000",
":+	c #000000",
"<+	c #000000",
"[+	c #000000",
"}+	c #000000",
"|+	c #000000",
"1+	c #000000",
"2+	c #000000",
"3+	c #000000",
"4+	c #000000",
"5+	c #000000",
"6+	c #000000",
"7+	c #000000",
"8+	c #000000",
"9+	c #000000",
"0+	c #000000",
"a+	c #000000",
"b+	c #000000",
"c+	c #000000",
"d+	c #000000",
"e+	c #000000",
"f+	c #000000",
"g+	c #000000",
"h+	c #000000",
"i+	c #000000",
"j+	c #000000",
"k+	c #000000",
"l+	c #000000",
"m+	c #000000",
"n+	c #000000",
"o+	c #000000",
"p+	c #000000",
"q+	c #000000",
"r+	c #000000",
"s+	c #000000",
"t+	c #000000",
"u+	c #000000",
"v+	c #000000",
"w+	c #000000",
"x+	c #000000",
"y+	c #000000",
"z+	c #000000",
"A+	c #000000",
"B+	c #000000",
"C+	c #000000",
"D+	c #000000",
"E+	c #000000",
"F+	c #000000",
"G+	c #000000",
"H+	c #000000",
"D r.r.r.r.r.r.r.r.r.r.r.-.D D D D D ",
"D r.U.U.U.U.U.U.U.U.r.U.u K D D D D ",
"D r.U.U.U.U.U.U.U.U.r.U.U.u K D D D ",
"D r.U.U.U.U.U.U.U.U.u u u u 0 D D D ",
"D r.U.U.U.U.U.U.U.U.U.U.U.u ( ` D D ",
"D r.U.U.U.U.U.U.U.U.U.U.U.u ^ R D D ",
"D r.U.U.U.U.U.U.U.U.U.U.U.u ^ R D D ",
"D r.U.U.U.U.U.U.U.U.U.U.U.u ^ R D D ",
"D r.U.U.U.U.U.U.U.U.U.U.U.u ^ R D D ",
"D r.U.U.U.U.U.U.U.U.U.U.U.u ^ R D D ",
"D r.U.U.U.U.U.U.U.U.U.U.U.u ^ R D D ",
"D r.U.U.U.U.U.U.U.U.U.U.U.u ^ R D D ",
"D r.U.U.U.U.U.U.U.U.U.U.U.u ^ R D D ",
"D r.U.U.U.U.U.U.U.U.U.U.U.u ^ R D D ",
"D r.U.U.U.U.U.U.U.U.U.U.U.u ^ R D D ",
"D r.u u u u u u u u u u u u [ @.D D ",
"D !.p [ ^ ^ ^ ^ ^ ^ ^ ^ ^ [ p D D D ",
"D D d.@.R R R R R R R R R @.D D D D "};

// zoom
const char * zoom_xpm[] = {
"18 18 257 2",
"  	c None",
". 	c #0C0C0C",
"+ 	c #252426",
"@ 	c #252526",
"# 	c #262527",
"$ 	c #262628",
"% 	c #292929",
"& 	c #2C2B2D",
"* 	c #2E2E30",
"= 	c #402810",
"- 	c #373638",
"; 	c #373737",
"> 	c #3C3B3E",
", 	c #3D3C3E",
"' 	c #403F42",
") 	c #414042",
"! 	c #424043",
"~ 	c #424144",
"{ 	c #444444",
"] 	c #49484B",
"^ 	c #4A494C",
"/ 	c #4E4C50",
"( 	c #525154",
"_ 	c #58565B",
": 	c #5A585C",
"< 	c #5A5A5A",
"[ 	c #5B595D",
"} 	c #5C5A5E",
"| 	c #5D5B5F",
"1 	c #5E5C60",
"2 	c #5E5E5E",
"3 	c #5F5D61",
"4 	c #5F5F5F",
"5 	c #636166",
"6 	c #656367",
"7 	c #656368",
"8 	c #656468",
"9 	c #686868",
"0 	c #69676C",
"a 	c #6A6A6A",
"b 	c #6C6A6E",
"c 	c #6E6C71",
"d 	c #408080",
"e 	c #717171",
"f 	c #727075",
"g 	c #737177",
"h 	c #737373",
"i 	c #747278",
"j 	c #757575",
"k 	c #767676",
"l 	c #77757A",
"m 	c #7A777D",
"n 	c #7A787E",
"o 	c #7B7B7B",
"p 	c #7C7A80",
"q 	c #7D7B80",
"r 	c #7F7D82",
"s 	c #7F7F7F",
"t 	c #817E84",
"u 	c #808080",
"v 	c #817F85",
"w 	c #827F85",
"x 	c #818181",
"y 	c #828086",
"z 	c #848288",
"A 	c #E63A3A",
"B 	c #89868D",
"C 	c #89878D",
"D 	c None",
"E 	c #8A888E",
"F 	c #8B898F",
"G 	c #8C8990",
"H 	c #8D8A91",
"I 	c #8D8B91",
"J 	c #8E8B91",
"K 	c #8F8D93",
"L 	c #908E94",
"M 	c #F63E3E",
"N 	c #928F96",
"O 	c #939097",
"P 	c #3E9AF6",
"Q 	c #949198",
"R 	c #959299",
"S 	c #949494",
"T 	c #96949A",
"U 	c #FF4040",
"V 	c #97949B",
"W 	c #97959B",
"X 	c #809F9F",
"Y 	c #979797",
"Z 	c #40A0FF",
"` 	c #9A979E",
" .	c #999999",
"..	c #9B989F",
"+.	c #9C99A0",
"@.	c #9D9AA1",
"#.	c #9D9BA2",
"$.	c #9E9BA3",
"%.	c #A09DA4",
"&.	c #A29FA6",
"*.	c #A5A2AA",
"=.	c #A6A3AB",
"-.	c #A8A5AC",
";.	c #AAA7AE",
">.	c #ABA7AF",
",.	c #60C0C0",
"'.	c #ABA8B0",
").	c #ACA9B1",
"!.	c #ADAAB2",
"~.	c #AEABB3",
"{.	c #B0ADB5",
"].	c #B1ADB5",
"^.	c #B0B0B0",
"/.	c #B2AEB6",
"(.	c #B2AFB7",
"_.	c #B3B0B8",
":.	c #B5B2BA",
"<.	c #B6B3BB",
"[.	c #B7B4BC",
"}.	c #B8B4BD",
"|.	c #B7B7B7",
"1.	c #B9B5BD",
"2.	c #B9B6BE",
"3.	c #BBB7BF",
"4.	c #BBB8C0",
"5.	c #BCB9C1",
"6.	c #BDBAC2",
"7.	c #FFA040",
"8.	c #BEBAC3",
"9.	c #BDBDBD",
"0.	c #BFBBC4",
"a.	c #C0BCC5",
"b.	c #C0BDC6",
"c.	c #C1BEC6",
"d.	c #C0C0C0",
"e.	c #C2BFC7",
"f.	c #C3C0C8",
"g.	c #C5C1CA",
"h.	c #90E63A",
"i.	c #C6C2CB",
"j.	c #C7C3CC",
"k.	c #C7C4CD",
"l.	c #C8C5CD",
"m.	c #C8C5CE",
"n.	c #C9C6CF",
"o.	c #CAC6CF",
"p.	c #CBC7D0",
"q.	c #CCC8D1",
"r.	c #CCCCCC",
"s.	c #CECAD3",
"t.	c #CECBD4",
"u.	c #CFCCD5",
"v.	c #D0CCD6",
"w.	c #D1CDD7",
"x.	c #D2CED8",
"y.	c #D3CFD8",
"z.	c #9AF63E",
"A.	c #D4D0DA",
"B.	c #D3D3D3",
"C.	c #D5D1DA",
"D.	c #D6D2DC",
"E.	c #D7D3DD",
"F.	c #D8D4DE",
"G.	c #D9D5DF",
"H.	c #DAD6E0",
"I.	c #A0FF40",
"J.	c #DBD7E1",
"K.	c #DCD8E1",
"L.	c #DCD8E2",
"M.	c #DDD9E3",
"N.	c #DEDAE4",
"O.	c #DFDBE5",
"P.	c #80FFFF",
"Q.	c #E3E3E3",
"R.	c #E6E6E6",
"S.	c #F6F6F6",
"T.	c #FCFCFC",
"U.	c #FFFFFF",
"V.	c #000000",
"W.	c #000000",
"X.	c #000000",
"Y.	c #000000",
"Z.	c #000000",
"`.	c #000000",
" +	c #000000",
".+	c #000000",
"++	c #000000",
"@+	c #000000",
"#+	c #000000",
"$+	c #000000",
"%+	c #000000",
"&+	c #000000",
"*+	c #000000",
"=+	c #000000",
"-+	c #000000",
";+	c #000000",
">+	c #000000",
",+	c #000000",
"'+	c #000000",
")+	c #000000",
"!+	c #000000",
"~+	c #000000",
"{+	c #000000",
"]+	c #000000",
"^+	c #000000",
"/+	c #000000",
"(+	c #000000",
"_+	c #000000",
":+	c #000000",
"<+	c #000000",
"[+	c #000000",
"}+	c #000000",
"|+	c #000000",
"1+	c #000000",
"2+	c #000000",
"3+	c #000000",
"4+	c #000000",
"5+	c #000000",
"6+	c #000000",
"7+	c #000000",
"8+	c #000000",
"9+	c #000000",
"0+	c #000000",
"a+	c #000000",
"b+	c #000000",
"c+	c #000000",
"d+	c #000000",
"e+	c #000000",
"f+	c #000000",
"g+	c #000000",
"h+	c #000000",
"i+	c #000000",
"j+	c #000000",
"k+	c #000000",
"l+	c #000000",
"m+	c #000000",
"n+	c #000000",
"o+	c #000000",
"p+	c #000000",
"q+	c #000000",
"r+	c #000000",
"s+	c #000000",
"t+	c #000000",
"u+	c #000000",
"v+	c #000000",
"w+	c #000000",
"x+	c #000000",
"y+	c #000000",
"z+	c #000000",
"A+	c #000000",
"B+	c #000000",
"C+	c #000000",
"D+	c #000000",
"E+	c #000000",
"F+	c #000000",
"G+	c #000000",
"H+	c #000000",
"r.r.r.r.r.r.r.r.r.r.r.-.D D D D D D ",
"r.U.U.U.U.U.U.U.U.r.U.u K D D D D D ",
"r.U.U.U.U.U.U.U.U.r.U.U.u K D D D D ",
"r.U.U.U.T.S.R.d.d.d.d.4 a 3 D D D D ",
"r.U.U.U.S.d.d.P.P.P.P.d.d., B D D D ",
"r.U.U.U.R.d.P.P.U.P.P.P.u @ c D D D ",
"r.U.U.U.d.P.P.U.U.U.U.P.P.u _ D D D ",
"r.U.U.U.d.P.U.U.U.P.P.P.P.u ~ D D D ",
"r.U.U.U.d.P.P.U.P.P.P.P.P.u - D D D ",
"r.U.U.U.d.P.P.U.P.P.P.P.P.u - ` D D ",
"r.U.U.U.9.d.P.P.P.P.P.P.u . , %.D D ",
"r.U.U.U.B.d.u P.P.P.P.u u 7.' #.D D ",
"r.U.U.U.R.9.x u u u u % = = 7.z D D ",
"r.U.U.U.S.Q.9.Y e 2 2 9 ; = = 7.H D ",
"r.U.U.U.T.S.R.B.9.^.^.|.< & = = 7.N ",
"r.u u u u u s o k h h j h ] 5 = = r ",
"D p [ ^ ^ ^ ^ ^ ^ ^ ^ ^ : i D N r G ",
"D D D D D D D D D D D D D D D D D D "};

// auto
const char * auto_xpm[] = {
"18 18 257 2",
"  	c None",
". 	c #0C0C0C",
"+ 	c #252426",
"@ 	c #252526",
"# 	c #262527",
"$ 	c #262628",
"% 	c #292929",
"& 	c #2C2B2D",
"* 	c #2E2E30",
"= 	c #402810",
"- 	c #373638",
"; 	c #373737",
"> 	c #3C3B3E",
", 	c #3D3C3E",
"' 	c #403F42",
") 	c #414042",
"! 	c #424043",
"~ 	c #424144",
"{ 	c #444444",
"] 	c #49484B",
"^ 	c #4A494C",
"/ 	c #4E4C50",
"( 	c #525154",
"_ 	c #58565B",
": 	c #5A585C",
"< 	c #5A5A5A",
"[ 	c #5B595D",
"} 	c #5C5A5E",
"| 	c #5D5B5F",
"1 	c #5E5C60",
"2 	c #5E5E5E",
"3 	c #5F5D61",
"4 	c #5F5F5F",
"5 	c #636166",
"6 	c #656367",
"7 	c #656368",
"8 	c #656468",
"9 	c #686868",
"0 	c #69676C",
"a 	c #6A6A6A",
"b 	c #6C6A6E",
"c 	c #6E6C71",
"d 	c #408080",
"e 	c #717171",
"f 	c #727075",
"g 	c #737177",
"h 	c #737373",
"i 	c #747278",
"j 	c #757575",
"k 	c #767676",
"l 	c #77757A",
"m 	c #7A777D",
"n 	c #7A787E",
"o 	c #7B7B7B",
"p 	c #7C7A80",
"q 	c #7D7B80",
"r 	c #7F7D82",
"s 	c #7F7F7F",
"t 	c #817E84",
"u 	c #808080",
"v 	c #817F85",
"w 	c #827F85",
"x 	c #818181",
"y 	c #828086",
"z 	c #848288",
"A 	c #E63A3A",
"B 	c #89868D",
"C 	c #89878D",
"D 	c #3A90E6",
"E 	c #8A888E",
"F 	c #8B898F",
"G 	c #8C8990",
"H 	c #8D8A91",
"I 	c #8D8B91",
"J 	c #8E8B91",
"K 	c #8F8D93",
"L 	c #908E94",
"M 	c #F63E3E",
"N 	c #928F96",
"O 	c #939097",
"P 	c #3E9AF6",
"Q 	c #949198",
"R 	c #959299",
"S 	c #949494",
"T 	c #96949A",
"U 	c #FF4040",
"V 	c #97949B",
"W 	c #97959B",
"X 	c #809F9F",
"Y 	c #979797",
"Z 	c #40A0FF",
"` 	c #9A979E",
" .	c #999999",
"..	c #9B989F",
"+.	c #9C99A0",
"@.	c #9D9AA1",
"#.	c #9D9BA2",
"$.	c #9E9BA3",
"%.	c #A09DA4",
"&.	c #A29FA6",
"*.	c #A5A2AA",
"=.	c #A6A3AB",
"-.	c #A8A5AC",
";.	c #AAA7AE",
">.	c #ABA7AF",
",.	c #60C0C0",
"'.	c #ABA8B0",
").	c #ACA9B1",
"!.	c #ADAAB2",
"~.	c #AEABB3",
"{.	c #B0ADB5",
"].	c #B1ADB5",
"^.	c #B0B0B0",
"/.	c #B2AEB6",
"(.	c #B2AFB7",
"_.	c #B3B0B8",
":.	c #B5B2BA",
"<.	c #B6B3BB",
"[.	c #B7B4BC",
"}.	c #B8B4BD",
"|.	c #B7B7B7",
"1.	c #B9B5BD",
"2.	c #B9B6BE",
"3.	c #BBB7BF",
"4.	c #BBB8C0",
"5.	c #BCB9C1",
"6.	c #BDBAC2",
"7.	c #FFA040",
"8.	c #BEBAC3",
"9.	c #BDBDBD",
"0.	c #BFBBC4",
"a.	c #C0BCC5",
"b.	c #C0BDC6",
"c.	c #C1BEC6",
"d.	c #C0C0C0",
"e.	c #C2BFC7",
"f.	c #C3C0C8",
"g.	c #C5C1CA",
"h.	c #90E63A",
"i.	c #C6C2CB",
"j.	c #C7C3CC",
"k.	c #C7C4CD",
"l.	c #C8C5CD",
"m.	c #C8C5CE",
"n.	c #C9C6CF",
"o.	c #CAC6CF",
"p.	c #CBC7D0",
"q.	c #CCC8D1",
"r.	c #CCCCCC",
"s.	c #CECAD3",
"t.	c #CECBD4",
"u.	c #CFCCD5",
"v.	c #D0CCD6",
"w.	c #D1CDD7",
"x.	c #D2CED8",
"y.	c #D3CFD8",
"z.	c #9AF63E",
"A.	c #D4D0DA",
"B.	c #D3D3D3",
"C.	c #D5D1DA",
"D.	c #D6D2DC",
"E.	c #D7D3DD",
"F.	c #D8D4DE",
"G.	c #D9D5DF",
"H.	c #DAD6E0",
"I.	c #A0FF40",
"J.	c #DBD7E1",
"K.	c #DCD8E1",
"L.	c #DCD8E2",
"M.	c #DDD9E3",
"N.	c #DEDAE4",
"O.	c #DFDBE5",
"P.	c #80FFFF",
"Q.	c #E3E3E3",
"R.	c #E6E6E6",
"S.	c #F6F6F6",
"T.	c #FCFCFC",
"U.	c None",
"V.	c #000000",
"W.	c #000000",
"X.	c #000000",
"Y.	c #000000",
"Z.	c #000000",
"`.	c #000000",
" +	c #000000",
".+	c #000000",
"++	c #000000",
"@+	c #000000",
"#+	c #000000",
"$+	c #000000",
"%+	c #000000",
"&+	c #000000",
"*+	c #000000",
"=+	c #000000",
"-+	c #000000",
";+	c #000000",
">+	c #000000",
",+	c #000000",
"'+	c #000000",
")+	c #000000",
"!+	c #000000",
"~+	c #000000",
"{+	c #000000",
"]+	c #000000",
"^+	c #000000",
"/+	c #000000",
"(+	c #000000",
"_+	c #000000",
":+	c #000000",
"<+	c #000000",
"[+	c #000000",
"}+	c #000000",
"|+	c #000000",
"1+	c #000000",
"2+	c #000000",
"3+	c #000000",
"4+	c #000000",
"5+	c #000000",
"6+	c #000000",
"7+	c #000000",
"8+	c #000000",
"9+	c #000000",
"0+	c #000000",
"a+	c #000000",
"b+	c #000000",
"c+	c #000000",
"d+	c #000000",
"e+	c #000000",
"f+	c #000000",
"g+	c #000000",
"h+	c #000000",
"i+	c #000000",
"j+	c #000000",
"k+	c #000000",
"l+	c #000000",
"m+	c #000000",
"n+	c #000000",
"o+	c #000000",
"p+	c #000000",
"q+	c #000000",
"r+	c #000000",
"s+	c #000000",
"t+	c #000000",
"u+	c #000000",
"v+	c #000000",
"w+	c #000000",
"x+	c #000000",
"y+	c #000000",
"z+	c #000000",
"A+	c #000000",
"B+	c #000000",
"C+	c #000000",
"D+	c #000000",
"E+	c #000000",
"F+	c #000000",
"G+	c #000000",
"H+	c #000000",
"U.U.U.U.U. . .U.U.U.U.U.U.U.U.U.U.U.",
"U.U.U. . .O.Z  .R U.U.U.U.U.U.U.U.U.",
"U. . .O.O.Z O. .8 U.U.U.U.U.U.U.U.U.",
" .O.O.U O.I.O.Z Y m  . .U.U.U.U.U.U.",
" .O.U O.I.O.Z O.S  .U U  . .#.U.U.U.",
">. .O.O.U O.I.L.D  .U U I.I. . .%.U.",
"U. .O.U O.I.O.P  .U U I.I.I.Z Z  .R ",
"U.#. .O.O.U L.h. .U U I.I.Z Z Z  .g ",
"U.U. .O.U O.z. .U U I.I.I.Z Z  .* b ",
"U.U.#. .O.L.A  .U U I.I.Z Z Z  .! U.",
"U.U.U. .O.M  .U U I.I.I.Z Z  .$ 1 U.",
"U.U.U.#.Y n. .U U I.I.Z Z Z  .! v U.",
"U.U.U.U.S  .U U I.I.I.Z Z  .+ 1 U.U.",
"U.U.U.U.T  .U U I.I.Z Z Z  .) U.U.U.",
"U.U.U.U.U.g  . .I.I.Z Z  .# 1 U.U.U.",
"U.U.U.U.U.&.g /  . .Z Z  .! U.U.U.U.",
"U.U.U.U.U.U.U.T q |  . .> U.U.U.U.U.",
"U.U.U.U.U.U.U.U.U.U.v b U.U.U.U.U.U."};

// gamma correction mono
const char * gamma_m_xpm[] = {
"30 20 31 1",
" 	c None",
".	c #000000",
"+	c #080808",
"@	c #111111",
"#	c #1A1A1A",
"$	c #232323",
"%	c #2B2B2B",
"&	c #343434",
"*	c #3D3D3D",
"=	c #464646",
"-	c #4F4F4F",
";	c #575757",
">	c #606060",
",	c #696969",
"'	c #727272",
")	c #7B7B7B",
"!	c #838383",
"~	c #8C8C8C",
"{	c #959595",
"]	c #9E9E9E",
"^	c #A7A7A7",
"/	c #AFAFAF",
"(	c #B8B8B8",
"_	c #C1C1C1",
":	c #CACACA",
"<	c #D3D3D3",
"[	c #DBDBDB",
"}	c #E4E4E4",
"|	c #EDEDED",
"1	c #F6F6F6",
"2	c #FFFFFF",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12"};


// gamma correction red
const char * gamma_r_xpm[] = {
"30 20 31 1",
" 	c None",
".	c #FF0000",
"+	c #FF0808",
"@	c #FF1111",
"#	c #FF1A1A",
"$	c #FF2323",
"%	c #FF2B2B",
"&	c #FF3434",
"*	c #FF3D3D",
"=	c #FF4646",
"-	c #FF4F4F",
";	c #FF5757",
">	c #FF6060",
",	c #FF6969",
"'	c #FF7272",
")	c #FF7B7B",
"!	c #FF8383",
"~	c #FF8C8C",
"{	c #FF9595",
"]	c #FF9E9E",
"^	c #FFA7A7",
"/	c #FFAFAF",
"(	c #FFB8B8",
"_	c #FFC1C1",
":	c #FFCACA",
"<	c #FFD3D3",
"[	c #FFDBDB",
"}	c #FFE4E4",
"|	c #FFEDED",
"1	c #FFF6F6",
"2	c #FFFFFF",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12"};


// gamma correction green
const char * gamma_g_xpm[] = {
"30 20 31 1",
" 	c None",
".	c #00FF00",
"+	c #08FF08",
"@	c #11FF11",
"#	c #1AFF1A",
"$	c #23FF23",
"%	c #2BFF2B",
"&	c #34FF34",
"*	c #3DFF3D",
"=	c #46FF46",
"-	c #4FFF4F",
";	c #57FF57",
">	c #60FF60",
",	c #69FF69",
"'	c #72FF72",
")	c #7BFF7B",
"!	c #83FF83",
"~	c #8CFF8C",
"{	c #95FF95",
"]	c #9EFF9E",
"^	c #A7FFA7",
"/	c #AFFFAF",
"(	c #B8FFB8",
"_	c #C1FFC1",
":	c #CAFFCA",
"<	c #D3FFD3",
"[	c #DBFFDB",
"}	c #E4FFE4",
"|	c #EDFFED",
"1	c #F6FFF6",
"2	c #FFFFFF",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12"};


// gamma correction blue
const char * gamma_b_xpm[] = {
"30 20 31 1",
" 	c None",
".	c #0000FF",
"+	c #0808FF",
"@	c #1111FF",
"#	c #1A1AFF",
"$	c #2323FF",
"%	c #2B2BFF",
"&	c #3434FF",
"*	c #3D3DFF",
"=	c #4646FF",
"-	c #4F4FFF",
";	c #5757FF",
">	c #6060FF",
",	c #6969FF",
"'	c #7272FF",
")	c #7B7BFF",
"!	c #8383FF",
"~	c #8C8CFF",
"{	c #9595FF",
"]	c #9E9EFF",
"^	c #A7A7FF",
"/	c #AFAFFF",
"(	c #B8B8FF",
"_	c #C1C1FF",
":	c #CACAFF",
"<	c #D3D3FF",
"[	c #DBDBFF",
"}	c #E4E4FF",
"|	c #EDEDFF",
"1	c #F6F6FF",
"2	c #FFFFFF",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12",
".+@#$%&*=-;>,')!~{]^/(_:<[}|12"};

// penguin
const char * penguin_xpm[] = {
"250 101 257 2",
"  	c None",
". 	c #000000",
"+ 	c #010101",
"@ 	c #020202",
"# 	c #040404",
"$ 	c #050505",
"% 	c #060600",
"& 	c #070707",
"* 	c #080808",
"= 	c #0A0A0A",
"- 	c #0B0B0B",
"; 	c #0D0D0D",
"> 	c #0F0F0F",
", 	c #101010",
"' 	c #121212",
") 	c #131313",
"! 	c #151515",
"~ 	c #171717",
"{ 	c #181818",
"] 	c #191918",
"^ 	c #1C1C1C",
"/ 	c #1D1D1D",
"( 	c #212118",
"_ 	c #21211C",
": 	c #232307",
"< 	c #222221",
"[ 	c #232323",
"} 	c #252525",
"| 	c #272727",
"1 	c #292929",
"2 	c #2B2B2A",
"3 	c #2E2E22",
"4 	c #2D2D2D",
"5 	c #303004",
"6 	c #303005",
"7 	c #313107",
"8 	c #2F2F2D",
"9 	c #313131",
"0 	c #333333",
"a 	c #383836",
"b 	c #383838",
"c 	c #3A3A3A",
"d 	c #3F3F02",
"e 	c #414108",
"f 	c #3E3E3E",
"g 	c #3F3F3F",
"h 	c #424242",
"i 	c #454545",
"j 	c #464646",
"k 	c #484848",
"l 	c #4C4C10",
"m 	c #4A4A4A",
"n 	c #4E4E04",
"o 	c #4D4D4D",
"p 	c #535303",
"q 	c #545409",
"r 	c #525252",
"s 	c #535353",
"t 	c #57571E",
"u 	c #585823",
"v 	c #555555",
"w 	c #565656",
"x 	c #595958",
"y 	c #595959",
"z 	c #5A5A5A",
"A 	c #5C5C5C",
"B 	c #5D5D5D",
"C 	c #62621A",
"D 	c #5E5E5D",
"E 	c #5F5F5F",
"F 	c #616161",
"G 	c #67671A",
"H 	c #64645F",
"I 	c #696908",
"J 	c #696925",
"K 	c #6A6A11",
"L 	c #656565",
"M 	c #68684A",
"N 	c #666666",
"O 	c #6A6A50",
"P 	c #686868",
"Q 	c #6D6D2F",
"R 	c #696969",
"S 	c #6B6B6B",
"T 	c #6D6D6C",
"U 	c #6D6D6D",
"V 	c #6E6E6E",
"W 	c #757500",
"X 	c #6F6F6F",
"Y 	c #787805",
"Z 	c #727272",
"` 	c #797906",
" .	c #747474",
"..	c #7B7B23",
"+.	c #787860",
"@.	c #767676",
"#.	c #787878",
"$.	c #7B7B65",
"%.	c #7A7A7A",
"&.	c #7B7B7B",
"*.	c #7D7D7D",
"=.	c #7E7E7E",
"-.	c #7F7F7F",
";.	c #818181",
">.	c #828282",
",.	c #8A8A02",
"'.	c #848484",
").	c #858584",
"!.	c #868686",
"~.	c #8E8E01",
"{.	c #8D8C5A",
"].	c #898989",
"^.	c #919101",
"/.	c #8B8B8B",
"(.	c #949401",
"_.	c #94941F",
":.	c #8D8D8D",
"<.	c #959500",
"[.	c #909076",
"}.	c #959535",
"|.	c #939450",
"1.	c #8F8F8F",
"2.	c #979718",
"3.	c #909090",
"4.	c #919191",
"5.	c #939393",
"6.	c #9B9B01",
"7.	c #9B9B0B",
"8.	c #949494",
"9.	c #9D9D01",
"0.	c #9E9E01",
"a.	c #969696",
"b.	c #9D9E3F",
"c.	c #989898",
"d.	c #A1A100",
"e.	c #999999",
"f.	c #A2A200",
"g.	c #9A9A9A",
"h.	c #9C9C92",
"i.	c #9C9C9C",
"j.	c #A5A501",
"k.	c #A2A264",
"l.	c #A1A172",
"m.	c #9D9D9D",
"n.	c #A6A600",
"o.	c #9F9F9F",
"p.	c #A8A800",
"q.	c #A8A925",
"r.	c #A1A1A1",
"s.	c #A2A2A2",
"t.	c #A5A682",
"u.	c #A5A5A4",
"v.	c #AEAE01",
"w.	c #A7A7A7",
"x.	c #AFAF68",
"y.	c #AAAAAA",
"z.	c #B5B503",
"A.	c #ADADAD",
"B.	c #B7B703",
"C.	c #B2B282",
"D.	c #B7B72A",
"E.	c #B0B0B0",
"F.	c #B1B1B1",
"G.	c #B2B2B2",
"H.	c #B6B68B",
"I.	c #B3B3B3",
"J.	c #BDBD01",
"K.	c #BEBE00",
"L.	c #B6B6B6",
"M.	c #BABA9D",
"N.	c #B8B8B8",
"O.	c #C2C20C",
"P.	c #BABABA",
"Q.	c #BBBBB3",
"R.	c #C5C502",
"S.	c #BCBCBC",
"T.	c #BDBDBD",
"U.	c #C4C47B",
"V.	c #CACA33",
"W.	c #C2C2C2",
"X.	c #CFCF01",
"Y.	c #C6C6C6",
"Z.	c #C9C9C9",
"`.	c #CBCBCB",
" +	c #CECECE",
".+	c #DBDB02",
"++	c #D0D0D0",
"@+	c #D6D6B7",
"#+	c #D4D4D4",
"$+	c #E2E226",
"%+	c #D7D7D7",
"&+	c #E5E501",
"*+	c #E2E271",
"=+	c #DADADA",
"-+	c #DCDCDC",
";+	c #DDDDDD",
">+	c #EEEE03",
",+	c #E3E3E3",
"'+	c #ECEC8D",
")+	c #F2F20A",
"!+	c #F3F314",
"~+	c #F6F604",
"{+	c #EBEBEA",
"]+	c #F0F0E9",
"^+	c #FEFE09",
"/+	c #FFFF22",
"(+	c #FFFF46",
"_+	c #F9F9BA",
":+	c #F4F4F4",
"<+	c #FFFF7D",
"[+	c #FAFAF9",
"}+	c #FFFFFF",
"|+	c #000000",
"1+	c #000000",
"2+	c #000000",
"3+	c #000000",
"4+	c #000000",
"5+	c #000000",
"6+	c #000000",
"7+	c #000000",
"8+	c #000000",
"9+	c #000000",
"0+	c #000000",
"a+	c #000000",
"b+	c #000000",
"c+	c #000000",
"d+	c #000000",
"e+	c #000000",
"f+	c #000000",
"g+	c #000000",
"h+	c #000000",
"i+	c #000000",
"j+	c #000000",
"k+	c #000000",
"l+	c #000000",
"m+	c #000000",
"n+	c #000000",
"o+	c #000000",
"p+	c #000000",
"q+	c #000000",
"r+	c #000000",
"s+	c #000000",
"t+	c #000000",
"u+	c #000000",
"v+	c #000000",
"w+	c #000000",
"x+	c #000000",
"y+	c #000000",
"z+	c #000000",
"A+	c #000000",
"B+	c #000000",
"C+	c #000000",
"D+	c #000000",
"E+	c #000000",
"F+	c #000000",
"G+	c #000000",
"H+	c #000000",
"N  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .N ",
" .Y.%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+Y. .",
" .%+;+`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.;+%+ .",
" .%+`.&. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .&.`.%+ .",
" .%+`. .e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e. .`.%+ .",
" .%+`. .g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g. .`.%+ .",
" .%+`. .i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.y.y.A.A.A.A.A.A.A.E.E.E.E.F.F.F.G.G.I.Y.%+=+=+=+-+-+;+;+;+Z.m.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i. .`.%+ .",
" .%+`. .m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.o.o.o.o.o.o.r.r.A.A.E.E.E.G.G.I.L.L.L.L.N.N.P.P.S.T.T.Z.Z.`.`.`. + + +++++++++#+#+#+%+%+%+%+%+%+%+=+=+=+=+-+;+;+`.o.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m. .`.%+ .",
" .%+`. .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.m.A.A.E.E.F.G.I.I.L.L.P.S.T.T.T.T.W.W.W.W.W.W.W.Y.Y.Y.Y.Y.Z.Z.Z.Z.`.`.`. + + + +++++++++#+#+#+#+%+%+%+%+%+=+=+=+=+-+;+`.m.m.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o. .`.%+ .",
" .%+`. .r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.o.F.I.L.L.L.L.N.N.N.P.P.P.S.T.T.T.T.W.W.W.W.W.W.W.W.Y.Y.Y.Z.Z.Z.Z.Z.`.`.`. + + + +++++++++#+#+#+#+%+%+%+%+=+=+=+=+=+;+`.m.o.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r. .`.%+ .",
" .%+`. .s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.o.F.I.L.L.L.L.N.N.N.N.P.P.S.T.T.T.T.T.W.W.W.W.W.W.W.Y.Y.Y.Y.Z.Z.Z.Z.`.`.`. + + + +++++++++++#+#+#+#+%+%+%+%+=+=+=+=+;+`.i.o.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s. .`.%+ .",
" .%+`.@.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.o.E.I.I.L.L.L.L.N.N.N.P.P.P.S.S.T.T.T.W.W.W.W.W.W.W.W.Y.Y.Y.Y.Z.Z.Z.Z.`.`.`. + + + +I.y.A.A.A.A.A.E.E.E.E.F.F.=+=+=+;+Z.g.s.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.@.`.%+ .",
" .%+`.@.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.o.E.I.I.I.I.A.y.w.u.u.u.w.w.w.w.w.e.E E F F F F F F F F F F F F H H H H H H L L L L | ! ! ~ h @.a.e.e.e.e.e.&.%+=+=+=+Z.e.u.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.@.`.%+ .",
" .%+`.@.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.r.E.G.I.I.F.u.m.e.8.5.4.*.i < < < ] . . . . + . . . . . . . . + + + + + + + + @ + + + . . . . > j !.w.w.w.w.>.%+%+=+=+Y.a.u.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.@.`.%+ .",
" .%+`.@.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.r.A.F.G.I.P.A.y.y.y.w.N ) . . . . . + = 9 o F o 1 $ + . + + + + @ @ @ @ ' 0 x P r 4 - @ @ + + . . $ s o.y.y.'.%+%+%+=+Y.a.w.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.Y.Y.Y.Y.W.T.T.T.T.G.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.@.`.%+ .",
" .%+`.@.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.r.A.F.G.I.Y.E.y.y.].< + . . . . $ i /.Z.;+{+{+]+]+Z.X ; + + + @ @ @ ^ ].=+]+]+]+{+,+Z.1.h $ @ + . . . { Z y.'.%+%+%+=+W.8.w.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.P.W.W.W.T.S.P.P.P.N.N.N.A.A.A.A.y.y.Z.Z.P.P.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.@.`.%+ .",
" .%+`.@.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.r.A.E.F.G. +I.w.R - . . . . $ h o.#+{+:+[+[+}+}+}+}+[+P.4 @ @ # * i ++[+}+}+}+}+}+[+[+]+;+o.0 & @ + + . * o =.%+%+%+=+W.8.w.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.L.T.Y.Y.W.E.o.m.a.5.4.4.1.:./.].].!.!.'.>.>.!.).'.g.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.@.`.%+ .",
" .%+`.@.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.s.A.E.E.F. +y.j * . . . . ! V `.,+:+[+}+}+}+}+}+}+}+}+}+Y./ & = h =+}+}+}+}+}+}+}+}+}+}+[+]+++Z , # @ @ + # i #+%+%+%+W.4.y.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.N.T.++Z.w.w.i.c.a.8.8.4.3.1.:././.].!.!.).>.;.-.-.*.&.%.#.&.y.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.@.`.%+ .",
" .%+`.@.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.s.y.E.E.F.`.m @ . . . . _ 8.%+{+[+}+}+}+}+}+}+}+}+}+}+}+[+1.> _ W.}+}+}+}+}+}+}+}+}+}+}+}+}+[+,+1._ & $ @ + b #+#+%+%+W.4.A.E.P.++%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+++Y.I.G.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.F.L.W.`.Y.A.A.e.e.c.a.8.5.4.3.1.:./.].].!.!.'.>.;.-.=.&.&.%.#.@. .5.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.@.`.%+ .",
" .%+`.@.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.s.y.A.E.E.`.] . . . . ^ m.-+]+[+}+}+}+}+}+}+}+}+}+}+}+}+}+:+| F :+}+}+}+}+}+}+}+}+}+}+}+}+}+}+[+{+y.~ = & # c #+#+#+%+T.1.A.G.P.Z.F.r.g.g.g.g.e.`.-+-+-+;+;+;+;+#+G.L.T.I.F.A.F.F.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.I.Z. +%+L.y.e.e.e.c.a.8.5.4.3.1.:./.].].].!.'.>.;.-.-.*.&.%.#.@.@. .&.T.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.@.`.%+ .",
" .%+`.@.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.s.y.A.E.E.`.] . . + * a.=+]+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+U L.}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+[+]+].! - * c #+#+#+%+T.:.A.I.I.W.%+T.w.u.W.;+L.W.=+=+=+-+-+;+;+#+G.G.E.y.s.m.a.1.a.4.E.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.L.Y.;+W.L.e.e.e.e.c.a.8.8.4.3.1.:././.].!.!.).>.;.-.=.*.&.%.#.@.@. .Z  .L.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.@.`.%+ .",
" .%+`.@.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.u.y.A.A.E.`.] + + + X ++{+[+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+m.=+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+[+,+N , - f #+#+#+%+T.:.E.L.A.Y.#+#+#+Y.w.=+I.W.=+=+=+=+=+=+-+#+G.G.A.w.s.m.a.4.].'.8.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.N.#+;+I.g.e.e.e.c.a.8.5.4.3.1.:./.].].!.!.'.>.;.-.=.&.&.%.#.@. .Z Z Z X c.W.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.@.`.%+ .",
" .%+`.#.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.u.y.A.A.A.`.] + + 9 W.,+[+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+Z.{+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+:+Z.0 ; f ++#+#+#+P./.E.L.w.Z.%+=+=+ +u.%+G.T.%+%+=+=+=+=+=+#+G.F.A.w.s.i.a.4./.!.5.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.N.++ +w.e.e.e.c.a.8.5.4.3.:.:./.].].!.!.).>.;.-.-.*.&.%.#.@.@. .Z Z X V ;.W.N.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.`.%+ .",
" .%+`.#.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.u.w.A.A.A.Z.^ + - ].%+]+}+}+}+}+}+[+[+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+[+[+}+}+}+}+}+}+[+{+]., f ++++#+#+P.].G.N.s. +=+%+%+`.u.#+E.T.%+%+%+%+%+%+=+#+G.F.A.w.r.g.a.4.].).5.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.Y.#+o.e.e.c.a.8.5.4.3.:.:./.].].!.).'.>.;.-.=.&.&.%.#.@. . .Z Z X U T X I.W.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.#.`.%+ .",
" .%+`.#.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.u.w.y.A.A.Z.^ + 8 Z.,+:+}+}+}+}+[+5.E ++}+}+}+}+}+}+}+}+}+}+%+:+}+}+}+}+}+}+}+}+}+}+s.x Y.}+}+}+}+}+}+:+Z.9 f ++++++#+N.].I.P.i.++;+%+#+Z.s.#+E.S.#+%+%+%+%+%+%+#+G.E.y.u.o.g.8.3.].'.5.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.=+N.c.a.a.8.5.4.3.1.:./.].].].!.'.>.;.-.=.*.&.#.#.@. . .Z Z X V T S R i.Y.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.#.`.%+ .",
" .%+`.#.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.u.w.y.A.A.Z.^ @ V ++{+[+}+}+}+}+8.# . Z }+}+}+}+}+}+}+}+}+}+4.=+}+}+}+}+}+}+}+}+}+:+c . ! {+}+}+}+}+}+[+,+P g ++++++#+N.!.I.P.a.#+-+#+++Y.r.++A.S.#+#+#+%+%+%+%+#+G.E.y.u.o.e.8.1.].'.5.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.Z.++o.a.8.5.4.3.:.:./.].].!.).).>.;.-.=.*.&.%.#.@.@. .Z Z X V T S R P %.`.T.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.#.`.%+ .",
" .%+`.#.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.w.w.y.y.A.Z.^ ) s.%+{+[+}+}+}+}+Z . * w.}+}+}+}+}+}+}+}+}+}+ .W.}+}+}+}+}+}+}+}+}+}+ .& @ Z.}+}+}+}+}+[+{+i.g ++++++#+L.!.L.T.4.=+=+++ +W.o. +A.P.#+#+#+#+#+#+#+#+G.E.y.s.m.c.5.:.].>.5.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.-+L.8.5.4.3.:.:./.].].!.).'.>.;.-.=.&.&.%.#.@. .Z Z Z X U T S R N N R S.W.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.#.`.%+ .",
" .%+`.#.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.w.u.y.y.y.Z.^ 1 W.=+{+[+}+}+}+}+=+>.s.:+}+}+}+}+}+}+}+}+}+[+z '.[+}+}+}+}+}+}+}+}+}+,+5.].[+}+}+}+}+}+}+{+W.k  +++++++L.'.N.T.1.;+=+++`.W.m.`.y.N.++++++#+#+#+#+#+G.A.y.s.m.a.4.:.!.>.5.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T. +#+e.4.3.:.:./.].].!.!.'.>.;.-.=.*.&.#.#.@. . .Z X X V T S R P N L L i.Z.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.#.`.%+ .",
" .%+`.#.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.w.u.y.y.y.Z.^ 0 `.;+{+[+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+Z.r s ,+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+]+++z  + +++++I.>.N.W.3.;+%+ +Z.T.m.Z.w.N.++++++++++++#+#+F.A.w.s.m.a.4./.!.;.5.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.=+L.3.:.:./.].].!.).>.>.;.-.=.&.&.#.#.@. . .Z X X U T S R N N L H F =.Y.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.#.`.%+ .",
" .%+`.#.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.w.u.w.y.y.Z.^ a ++;+{+[+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+[+/.w o L.}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+]+++N  + + +++G.;.P.W.3.;+%+Z.Y.S.g.Y.w.N. + +++++++++++#+F.A.w.r.i.a.3./.).-.5.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W. +-+1.:./.].].!.!.'.>.;.-.=.*.&.#.#.@. .Z Z Z X V T R R P N L H F E S P.Y.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.#.`.%+ .",
" .%+`.#.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.w.s.w.y.y.Z.^ a ++;+{+[+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+++s A E x {+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+[+{+++L  + + +++G.;.P.W.3.;+#+Z.W.P.g.W.u.L. + + + +++++++#+E.y.w.o.g.8.3./.).-.5.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.Z.-+F./.].].!.).'.>.;.-.=.*.&.%.#.@. . .Z X X V T S R N N L H F E E B r.Z.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.#.`.%+ .",
" .%+`.#.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.w.s.w.w.y.Z.^ 0 ++;+{+:+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+]+#.y E N D o.}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+[+{+Z.s  + + + +E.-.S.Y.4.;+#+Y.W.L.e.W.s.L. + + + + + + +#+E.y.u.o.g.8.1.].'.-.5.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.%+#+/.].!.).>.>.;.-.=.&.%.#.#.@. .Z Z X X U S S R N N L H F E D A A !.Z.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.#.`.%+ .",
" .%+`.#.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.w.s.w.w.w.Z.^ | W.;+{+:+[+}+}+}+}+}+}+}+}+}+}+}+}+}+[+m.x B L R U N Z.}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+[+{+E.h `. + + +E.=.T.Y.4.;+++W.T.I.a.T.r.L.`.`.`.`. + + +#+E.y.u.m.e.5.:.].>.=.5.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.`.=+A.!.!.'.>.;.-.=.*.&.#.#.@. .Z Z X X V T R R P N L H F E E B z z L W.`.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.#.`.%+ .",
" .%+`.%.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.y.r.w.w.w.Y./ , g.;+,+{+[+}+}+}+}+}+}+}+}+}+}+}+}+}+Z.O O ..,.{.{.$.$.{+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+:+,+&.h `.`. + +A.&.W.Z.4.;+++W.P.G.a.S.o.I.Z.Z.`.`.`.`.`.#+A.y.s.m.c.4.:.].>.*.5.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.#+ +:.>.>.;.-.*.&.&.#.#.@. .Z Z X V U T R R N L L H F E D B z z x w y.`.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.%.`.%+ .",
" .%+`.%.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.y.r.u.w.w.Y./ # k =+,+{+:+}+}+}+}+}+}+}+}+}+}+[+_+*+z.J.X.X..+.+.+X.O.V.'+]+[+}+}+}+}+}+}+}+}+}+}+}+[+{+Y.b h `.`.`. +A.&.W.`.4.-+ +T.N.E.a.N.m.G.Z.Z.Z.Z.Z.Z.`.#+A.w.s.i.a.4./.!.;.&.5.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`. +-+y.>.-.-.=.&.&.#.#.@. .Z Z Z X U T R R P N L H F E D B z z y w w %.++`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.%.`.%+ .",
" .%+`.%.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.y.o.u.w.w.Y./ # ; /.,+{+]+[+}+}+}+}+}+}+_+'+$+.+.+.+.+$+$+&+>+>+>+>+&+&+$+$+$+*+'+[+}+}+}+}+}+}+}+}+:+,+R ! h Z.`.`. +y.%.W.`.5.-+ +P.L.A.e.L.m.G.Z.Z.Z.Z.Z.Z.Z.++A.w.s.i.a.4./.!.;.&.8.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.%+ +/.-.*.*.&.#.#.@. .Z Z X V V T R R N N L H F E E B z z x w w v E Y.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.%.`.%+ .",
" .%+`.%. + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +y.o.u.u.w.Y./ # $ ] s.,+{+:+[+}+[+_+*+.+.+.+$+&+&+&+>+>+)+~+~+^+^+~+~+~+!+)+>+>+&+&+&+'+_+[+}+}+}+[+,+=._ ! h Z.Z.`.`.y.#.W. +5.=+ +N.G.A.i.I.g.F.Y.Y.Y.Z.Z.Z.Z.++y.w.r.g.a.3./.!.-.&.5. + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +++;+y.*.&.%.#.#.@. .Z Z X V U S R R N D s m m f c h k j r s y v v A y.++ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +%.`.%+ .",
" .%+`.%. + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +y.o.u.u.u.Y./ $ $ * ~ L P.;+]+'+.+.+$+&+&+>+>+)+!+~+~+^+^+^+/+/+/+/+/+^+^+^+^+^+~+~+!+>+>+&+'+]+,+L.r [ ] ) g Z.Z.`.`.w.@.W. +5.=+`.L.E.y.o.G.e.E.Y.Y.Y.Y.Y.Y.Y.++y.u.o.g.8.1.].).-.%.5. + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +%+;+!.&.#.@.@. .Z Z X X U T R P N w 8 ) = @ . . . . + $ - ' / c m =.`. + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +%.`.%+ .",
" .%+`.&.++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++y.m.s.u.u.Y./ $ & * - > } M X..+&+>+>+!+~+~+^+^+^+^+/+/+/+/+/+/+/+/+/+/+/+/+/+/+/+/+^+^+^+~+>+R.M 0 } / ] ) g Z.Z.Z.Z.w. .Y.++8.=+Z.I.A.y.s.E.c.E.W.W.W.Y.Y.Y.Y.++y.u.o.e.8.:.].'.=.#.5.++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;+T.&.@.@. .Z Z X V U T R P N A 4 ; + . . . . . . . . . . . . . - 2 L w.`.++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++&.`.%+ .",
" .%+`.&.#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+y.m.s.s.u.Y./ $ & * - > l K.&+>+~+~+^+^+/+/+/+/+/+/+/+/+/+/+/+(+(+(+(+/+/+/+/+/+/+/+/+/+/+/+^+~+O.e } / ] ) g Z.Z.Z.Z.w. .Z.#+8.=+Z.F.y.w.u.A.e.E.W.W.W.W.W.W.Y.++w.s.m.c.5.:.].>.*.#.5.#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+%+;+:.@. .Z Z X X U T R R N N w ' . + + + + + + + + . . . . . . . . . . - w y.++#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+&.`.%+ .",
" .%+`.&.#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+A.m.s.s.u.Y./ $ & * - ( v.&+)+~+^+/+/+/+/+/+/+/+/+/+/+/+(+(+<+_+_+<+(+(+(+(+/+/+/+/+/+/+/+/+/+/+~+2.} / ] ) g Y.Z.Z.Z.u.Z Z.#+8.=+Y.A.w.w.w.y.g.E.W.W.W.W.W.W.W.++w.s.m.c.5.:.].>.*.@.5.#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+=+W. .Z Z X V U T R P N N H i > . . + + @ @ @ @ + + + + . . . . . . . . . . * F W.#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+#+&.`.%+ .",
" .%+`.&.%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+A.i.r.s.s.W./ $ & = ; 6 R.&+>+~+~+^+^+/+/+/+/+/+/+/+/+(+(+<+<+<+(+(+/+/+/+/+/+/+/+/+/+/+/+/+^+^+!+v.[ / ] ) g Y.Y.Z.Z.u.Z Z.%+8.%+Y.y.u.w.y.w.g.F.W.W.W.W.W.W.W.++w.s.m.a.4./.!.>.&.@.8.%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+=+%+1.Z X V U S R P N L H H g & . + + @ @ @ @ # # @ @ @ @ + + + . . . . . . . . @ 1 m.%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+&.`.%+ .",
" .%+`.&.%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+A.g.r.r.s.W./ $ * = ; ~ ~..+&+&+>+>+)+!+~+~+^+^+^+^+^+/+/+(+(+/+/+/+/+/+^+^+^+^+^+^+^+~+~+!+>+&+X.G [ / { ) g Y.Y.Z.Z.s.X `.%+8.%+W.y.r.u.A.u.i.I.T.T.W.W.W.W.W.++w.r.i.a.4./.!.;.&.@.5.%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+-+W.X X U T R P N N L F F v > . + @ @ @ # $ $ $ $ $ $ # # @ @ @ + + + . . . . . . . ; @. +%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+&.`.%+ .",
" .%+`.&.=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+A.g.o.r.s.W./ $ * - ; ' 7 2.X..+.+$+$+$+&+&+&+&+>+>+>+)+~+~+^+^+~+~+~+!+)+)+>+>+>+&+&+$+$+.+X.B.Y 8 [ / { ' g Y.Y.Y.Y.r.V `.=+a.%+W.w.m.s.E.s.m.I.T.T.T.T.T.T.W. +u.o.g.8.3.].).-.%. .5.=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+:.T S R P N L L F F E o , . + @ @ @ # $ $ * * * * * & & $ $ @ @ @ + + . . . . . . . * E W.%+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+&.`.%+ .",
" .%+`.&.=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+A.g.o.o.r.W./ $ * - > ) { } K v.V.X.X..+.+.+.+.+.+.+.+.+.+$+&+&+&+$+$+.+.+.+.+X.X.X.X.V.O.z.(.u 0 4 [ / { ' g Y.Y.Y.Y.o.V  +=+a.%+W.u.g.r.I.o.m.I.S.T.T.T.T.T.T. +u.o.g.8.1.].'.-.#. .5.=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+;+W.S R R N L L F F E D w ! . + @ @ @ # $ & * = = - - - ; - = * $ # @ @ + + . . . . . . . @ b F.=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+&.`.%+ .",
" .%+`.&.-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+A.g.o.o.r.W./ $ * - > ) ] / } 8 G q.V.V.V.X.X.X.X.X.X.X.X.X.X.X.X.X.V.R.R.R.O.K.J.B.D.D.~.u h c 0 2 [ / { ' g W.Y.Y.Y.m.U  +-+a.%+W.Z.W.Y.L.m.m.I.P.S.S.S.T.T.T. +u.o.g.8.1.].>.=.#.Z 5.-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+;+'.P N N L F F E D B w 2 + . + @ @ # # $ * = ; ; , ' ) ) ) , ; = $ # @ @ + . . . . . . . . . ) u.-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+&.`.%+ .",
" .%+`.&.;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+A.e.m.o.o.W./ $ * ; , ! ^ < 1 v y.,+{+,+%+@+U.U.U.R.R.R.R.R.O.J.J.B.D.D.x.x.x.H.Y.%+{+[+,+y.r b 9 2 [ / ~ , g W.W.Y.Y.m.U ++;+a.%+S.T.T.W.T.G.y.L.P.P.P.P.P.S.S. +s.m.e.5.:.].>.=.@.Z 5.;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+N.P L H F F E B A z y 0 + + + + @ # $ $ * - ; ' ! { ^ / / / ] ! , - * $ @ @ + + . . . . . . . . , P.;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+&.`.%+ .",
" .%+`.%.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.o.c.m.m.o.W./ & = ; ) ] / 0 1.;+:+:+:+:+[+[+:+{+-+++Y.Q.M.H.H.C.C.y.A.I.W.#+,+:+}+}+}+}+}+}+%+#.b 2 [ ^ ~ , j W.W.Y.W.g.T P.Y.1.P.T.T.W.W.W.S.N.N.N.N.N.P.P.P.P. +s.m.c.4.:.!.>.*.@.Z ].Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.++;+*.L F F E D A z y x h * . + + @ @ $ $ * - > ) ] / < } | | | [ / { , - * $ @ @ + + . . . . . . . . h T.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.%.`.%+ .",
" .%+`.#.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.g.a.m.m.o.W./ & - > ) ^ f L.:+:+:+:+:+[+[+}+}+}+}+[+:+]+,+ +`.Z.Z.;+{+:+[+}+}+}+}+}+}+}+}+}+}+:+4.9 < ^ ! , r W.W.W.W.g.S L.T./.I.I.L.W.1.!.).>.y.L.N.N.N.N.N.N. +r.i.a.4./.!.;.&.@.Z ].T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.W.=+L.N E E B A z y w w v ] . + + @ @ # $ & = > ! ^ < } 1 4 8 9 9 4 | < ] ' - * $ @ @ + . . . . . . . . # -.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.#.`.%+ .",
" .%+`.#.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.g.a.i.m.m.W./ & - > ) | L.}+}+}+[+[+:+[+}+}+}+}+}+}+}+}+[+[+[+[+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+[+>./ ] ) > D W.W.W.W.c.R I.T./.I.I.I.%+S.u.e.].u.L.L.L.L.L.N.N. +o.g.a.3./.).-.&. .X !.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.`.;+&.E D A z z x w v v 0 @ . + + @ @ $ $ * ; ! ^ < | 4 9 0 b b b a 9 2 < ] ' - * $ # @ + . . . . . . . . | w.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.#.`.%+ .",
" .%+`.#.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.e.a.i.m.m.W./ & = ; ) -.[+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+}+:+f ! , - R W.W.W.W.c.R G.S./.G.G.I.=+W.y.e.].s.L.L.L.L.L.L.L. +o.g.a.3.].'.-.%. .X !.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.W.%+P.D A z y w w w @.-.&.) . + + @ @ # $ * - ) ] < | 4 0 b c g h h g c 0 4 < ] ' ; * $ @ @ + . . . . . . . + o L.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.#.`.%+ .",
" .%+`.#.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.a.8.g.i.m.W.X F H L R -+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+[+P.R N F g.W.W.W.W.a.R F.P.].F.F.F.=+Y.A.g.].s.I.I.I.L.L.L.L. +o.g.8.1.].>.=.#.Z V '.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.Z.%+=.z y Z #.5.w.w.y.y.y . . + + @ @ # $ * > ~ / [ 2 9 a f h i k k k i f a 2 < { ' - * $ @ + + . . . . . . . , 4.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.#.`.%+ .",
" .%+`.#.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.a.8.g.g.i.s.y.y.A.A.A.A.A.E.E.E.E.F.G.G.I.I.I.L.L.L.L.L.N.N.N.N.P.P.P.S.S.T.T.T.T.T.W.W.W.W.W.W.W.W.W.Y.Y.Y.W.W.W.W.W.8.P E.N.].E.E.E.=+Z.I.m.].r.G.I.I.I.I.I.I.`.m.e.8.:.].>.*.#.Z U >.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.S.#+Y.:.s.s.A.E.E.A.A.A.o._ . . + + @ @ # & - ' ] _ | 4 0 c h j m o r o o j f 0 2 _ { , - * $ @ + + . . . . . . + | -.m.L.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.#.`.%+ .",
" .%+`.#.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.8.8.g.g.i.i.m.m.m.o.o.o.r.s.s.s.u.u.u.w.w.w.w.y.y.y.y.A.A.A.A.A.E.E.F.F.G.I.I.I.L.L.L.L.N.N.N.P.P.P.S.T.T.T.T.T.W.W.W.8.N A.L.].A.A.A.=+ +N.o.].o.F.F.G.G.G.I.I.`.m.c.5.:.].>.*.@.Z T >.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.G.N.I.I.I.G.G.F.F.E.E.E.).$ . + + + @ @ $ * ; ) ^ < | 4 0 f i m o s w w s o j c 9 | / ~ , - & # @ + + . . . . . . . $ | o &.y.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.#.`.%+ .",
" .%+`.@.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.4.8.e.g.g.g.i.m.m.m.o.o.o.r.s.s.s.u.u.u.w.w.w.w.y.y.y.y.A.A.A.A.E.E.E.E.F.G.I.I.I.L.L.L.L.N.N.N.P.P.P.S.T.T.T.T.T.W.W.4.N y.I.!.A.A.A.-+#+S.s.].o.E.E.E.F.F.F.G.`.i.a.4./.!.;.&.@.Z S -.I.I.I.I.I.I.I.I.I.I.I.I.I.L.L.I.I.I.I.I.I.I.I.I.y.i.I.L.L.I.I.I.I.G.G.E.o . . + + @ @ @ $ * ; ) ^ < 1 8 a g j o r w z A z v o h b 4 } ^ ! ; = & # @ + . . . . . . . . / } , y I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.@.`.%+ .",
" .%+`.@.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.3.5.e.e.g.g.g.i.m.m.m.o.o.o.r.s.s.s.u.u.u.w.w.w.w.y.y.y.y.A.A.A.A.E.E.E.F.F.G.I.I.I.L.L.L.L.N.N.N.P.P.P.S.T.T.T.T.W.T.4.N y.F.!.y.y.A.-+%+W.w.].m.A.E.E.E.E.E.E.`.g.a.4./.!.-.&.@.X R -.F.F.F.F.F.F.F.F.F.F.F.F.Y.++ +++F.F.F.F.F.F.F.F.y.e.w.N.L.L.L.L.L.I.I.w.1 . + + + @ @ @ $ * ; ) ] < | 8 a g j o v A E F E z s k f 0 2 < ] ) ; * $ # @ + . . . . . . . * 0 m :.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.@.`.%+ .",
" .%+`.@.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.1.;.!.!.!.!.].]././.8.o.o.o.r.r.s.s.u.u.u.w.w.w.w.w.y.y.y.A.A.A.A.A.E.E.E.F.G.I.I.I.L.L.L.L.L.N.N.P.P.P.S.S.T.T.T.T.T.3.N w.E.!.y.y.y.=+=+Y.A.].m.A.A.A.A.E.E.E.`.g.8.3.].).-.%. .X R -.E.E.E.E.E.E.E.E.E.E.L.++w.!.!.c.++++Z.Z.Z.Z.Z.Z.N.e.e.w.P.L.L.L.L.L.I.o._ + + + + @ @ @ $ = ; ) ] _ | 4 a g j o w B F L L E x o h a 4 } / ~ ' ; * $ @ + + . . . . . . = 1.A.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.@.`.%+ .",
" .%+`.@.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.y.s.s.s.s.s.s.s.u.u.c.]././.:.:.1.3.4.4.4.5.3.>.>.>.>.'.).!.s.s.u.u.w.w.w.w.y.y.y.A.A.A.E.E.F.F.G.L.N.P.P.S.T.T.T.T.T.1.N w.A.).y.y.y.=+-+`.F./.i.A.A.A.A.A.A.A.Z.g.8.3.].'.=.#. .V R =.A.A.A.A.A.A.A.A.A.A.s.5.S.G.y.g.>.>.a.a.a.a.a.a.a.e.g.i.F.P.N.N.N.F.A.4.! + + @ @ @ @ @ $ * ; ) { / } 4 0 f j o w D L N N H z r h b 4 | _ ] ) > = $ # @ + . . . . . . . z A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.@.`.%+ .",
" .%+`.@.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.m.#.@.@. .Z Z X #.#.#.@.@.@. . . . . . .@.@.@.@.@.m.y.y.A.A.A.E.E.F.G.I.I.5.>.y.A.).w.w.w.=+-+ +L.1.g.y.y.y.A.A.A.A.Z.e.8.1.].>.*.#.Z U P *.A.A.A.A.A.A.A.A.A.A.w.!.8.L.Y.L.A.A.e.e.e.e.e.e.e.g.m.m.s.P.P.P.P.N.A.5.] @ @ @ @ @ @ @ $ * - , ! / [ 2 0 c i o w E L R R N D r i b 4 } _ ] ) , - * $ @ + + . . . . . . } m.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.@.`.%+ .",
" .%+`.@.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.w.w.w.w.w.w.w.w.y.y.y.y.y.y.y.y.y.y.y.y.y.y.e.4.4.3.:././.].].!.).>.>.;.-.*.&.%.#.@.@. .Z Z X m.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.'.w.w.w.=+;+#+P.4.g.y.y.y.y.y.y.y.Z.c.5.:.].>.&.@.Z T N *.y.y.y.y.y.y.y.y.y.y.y.y.i.!.1.P.N.y.y.y.y.y.y.y.u.m.o.o.r.w.S.S.S.P.G.g.[ # # # # @ @ @ $ * - > ) ^ < | 9 c h o v D L R S N E r h a 2 [ / { ) > - * $ # @ + + . . . . . @ Z y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.@.`.%+ .",
" .%+`.@.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.u.].&.&.&.&.&.&.&.>.].].].].].].].].].].].].].].r.w.w.w.w.u.u.u.s.s.r.o.m.m.g.e.c.a.8.8.4.3.1.:./.s.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.>.u.u.u.=+;+%+W.a.e.w.w.w.y.y.y.y.Z.a.4.:.!.>.&.@.Z S N ].`.`.`.`.`.`.Z.w.w.w.w.w.w.w.m.).w.w.w.w.w.w.w.w.:.1.r.s.u.u.E.W.T.T.T.A.a & & $ $ $ $ # # $ = ; ' { / } 4 a g m s B L R R N B o h 9 } / { ) , ; = & $ # @ + + . . . . . . i w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.@.`.%+ .",
" .%+`.@.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.1.*.:.3.].T @.3.3.>.P ;.#.Z /.:.>.*.:.:.:./.*.*./.-.&.&.&.&.&.&.&.&.&.&.&.&.&.&.].1.1.1.1.:./././.].:.:.:.:.a.w.w.w.w.w.w.w.w.w.w.w.>.u.u.u.=+;+=+W.e.e.w.w.w.w.y.y.y.Z.a.4./.!.;.&.@.Z S N Z !.!.!.!.!.!.:.Y.Y.Y.Y.Y.W.W.Y.G.1.Y.w.w.w.w.w.w.].h s.u.u.w.y.N.W.T.T.T.R - - * & $ $ $ # $ * - , ! ^ < 2 0 f j r z H P R L z o c 4 < { ' > - * & $ $ # @ + + . . . . . . ] 8.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.@.`.%+ .",
" .%+`.@.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.5.-.].3.3.-. .X  .&.Z Z @.:.!.S >.]./.].3.3./.#.Z *.1.!.).#.U /.!.'.].3.3.!.'.].3./.>.].].].].].]./././././././.!.-.-.-.-.-.-.-.m.u.u.u.>.s.s.s.=+;+-+Z.g.a.w.w.w.w.w.w.w.Z.8.3./.).-.%. .X R N #.g.g.g.g.g.g.c.-.-.-.-.>.8.8.:.).r.y.u.u.u.u.u.u.u.o L w.w.y.y.A.S.W.W.T.s.^ , ; - * * * & $ & = ; ) ] _ | 9 c i o x F L N F x k a | ^ ' - * $ # # @ @ @ @ + + . . . . . . - =.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.@.`.%+ .",
" .%+`. .s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.i.].).1.3.3.3.&.!.].-.&.].].1.4.>.@.#.!.:././.].&.&.%.].4.'.Z >.].4.!. .1.8.8.%.Z ).8.!.S ).5.a.8.#.Z !.e.e.e.-.>.3.e.4.a.a.4.g.i.c.E s.s.s.;.r.s.s.=+;+;+ +o.a.u.u.u.u.w.w.w.Z.8.1.].'.-.#. .X R N %.s.s.s.s.s.s.s.s.s.s.s.r.5.5.c.s.s.s.s.s.s.s.s.s.s.g.b @.y.A.A.E.F.Z.W.W.N.j ] ) > ; - = * * & * - , ! ^ [ 4 a g m s A F H D s h 9 < ) - $ @ @ @ @ + + + + + + . . . . . . @ X s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s. .`.%+ .",
" .%+`. .r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.o.!.>./.5.3.:.4.5.:.5.5.8.8.8.8.8.a.4.4.a.c.!.-.!.3.>.1.1.g.8.'.&.&.i.i.a.).).4.m.i.o.o.o.g.1.=.:.r.g.1.1.g.s.s.s.>.X =.s.#.4.g.3.s.r.e.z r.r.r.-.o.o.r.=+;+;+++s.8.s.s.w.r.o.s.u.Z.8.1.].>.=.#.Z V P N %.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r. .0 w.A.E.F.I.N.Z.W.W.o.} ^ ) , ; - - = * * = ; ) ] _ 1 9 c i o x B B w o c 1 ] - @ @ . . . . . . . + + + . , : @ . . * #.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r. .`.%+ .",
" .%+`. .o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.5.>.8.i.m.e.5.g.m.4.a.4.1.a.g.5.:.1.m.s.s.s.o.:.3.a.s.r.a.a.i.o.a.r.w.w.w./.3.a.w.i.'.8.8.y.s.8.5.8.A.u.5.5.r.A.A.A.A.E.E.E.g.w.E.F.y.o./.s o.o.o.-.o.o.o.=+;+;+%+w.8.s.s.W./.&.1.u.Y.5.:.].>.*.@.Z U N N ].o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.#.0 w.G.I.L.L.S.Z.Y.W.s [ ^ ! ) , ; - * $ * - , ! ^ [ 4 a g k r w w o h 9 / ; # . . . . . . . . . . . . @ I v.n @ . , ;.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o. .`.%+ .",
" .%+`. .m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.g.].4.s.u.u.w.u.u.w.y.y.y.s.w.y.u.r.y.y.y.c.c.g.e.a.o.u.w.8.g.m.w.A.w.w.u.y.G.F.G.I.I.A.i.i.y.L.A.g.g.y.L.w./.m.L.s.!.!.a.A.).'.E.P.P.I.u.4.&.o m.m.m.-.m.m.m.=+;+;+=+w.8.r.r.W.s.:.1.s.Y.4.:.].>.*.@.Z T &.g.i.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.9 &.I.L.L.N.N.Z.Z.Y.w.c [ ^ { ! , * @ # $ * ; , ~ / | 9 c h m o o j b } ) $ + . . . . . . . . . . . . 5 K.K.6.d @ [ a.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m. .`.%+ .",
" .%+`. .g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.:.].w.F.A.A.E.y.A.F.F.y.w.y.w.w.w.E.F.F.L.L.I.I.L.L.L.N.N.N.L.N.P.P.I.y.A.u.E.s.m.s.T.T.I.s.I.I.W.L.T.W.W.I.F.A.I.S.I.w.S.W.w.:.N.W.Y.S.y.a.>.V m g.g.g.=.i.u.u. +%+#+++y.a.o.o.N.`.Z.A.s.W.4./.!.;.&.Z &.8.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.4.c &.L.N.P.S.T.`.Z.Y.).9 < / ~ * @ @ @ $ & - ; ) ^ < 2 9 c h i h c 4 ^ = + . . . . . . . . . . . . . W X.z.6.,.: f i.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g. .`.%+ .",
" .%+`. .e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.3.!.s.P.P.P.S.S.S.N.T.T.T.P.P.T.F.N.P.T.E.E.N.E.E.E.F.P.T.T.W.W.T.T.W.T.T.W.Y.Y.Y.A.P.T.Z.Z.T.y.y.L.Z.u.W.`.`.m.o.w.w.I.w.w.L. +T.W. + +Y.F.m.].Z A S e.e.g.m.E.T.T.N.E.u.a.1.a.m.o.o.o.o.o.o.P.3./.!.=. .].a.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.:.9 3.P.S.T.W.W.++Z.W.R | ^ & . . + $ > * * - , ! ^ [ 2 0 b c b 9 < , # . . . . . . . . . . . . . # n.R.v.6.6.W +.A.g.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e. .`.%+ .",
" .%+`. .a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.!.o.S.W.W.W.W.W.W.Y.Y.Y.Y.Z.Z.Z.Z.Z.Z.Z.Z.Z.`.Y.A.N.W.Y.I.A.A.Y.W.A.E.Z.y.A.L. +L.L.L.T. +L.L.W.#+++++#+Y.++#+%+Y.`.%+%+T.L.Y.#+#+w.=+=+ +I.u.1.@.B @.a.8.c.u.G.T.Z.`.W.N.y.g.:.].m.m.m.m.m.m.o.L.1.].%.*.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.E k N.T.W.W.W.`.++`.F.c & $ + . $ ) ! ' ; = - , ~ / [ 2 8 9 4 [ ! & + . . . . . . . . . . . . . ( O.J.j.6.6.<.b.L.E.G.c.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a. .`.%+ .",
" .%+`. .8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.&./.:.1.4.8.4.5.g.G.I.I.L.L.L.N.Y.#+#+#+#+#+#+%+%+%+%+%+%+%+%+%+=+=+=+=+Y.%+=+=+Y.Y.Y.%+P.P.Y. +%+G.y.;+;+Z.W.W.++%+W.Y.,+W.W.-+ +W.,+#+L.y.8.-.o >.8.;.].e.w.L.W.#+%+Z.P.A.m.1.].g.i.i.i.m.m.m.A.&.=.:.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.H g W.W.W.Y.Z. +#+`.w & @ @ # ^ < ^ { ! , * - , ~ ^ < } } < { ; @ . . . . . . . . . . . . . . d R.z.d.6.<.6.7.t.N.N.s.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8. .`.%+ .",
" .%+`. .8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.*.U X Z Z  .#.&.=.;.'.]./.:.4.8.e.m.o.r.u.w.w.y.A.E.F.`. +++++++++#+#+#+%+%+,+,+,+,+{+{+,+{+{+{+=+y.`.{+{+ +Y.Y.{+G.W.=+++Z.++ +A.=+-+L.A.i. .o h >.&.#.].a.u.I.T.`. +Y.N.y.g.:.-.%.%.%.%.&.!.g.8.1.5.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.5.k g.W.Y.Z.Z.Z.++y.] # . * ] 0 4 } _ ^ ) $ * - , ! ] ^ ^ ~ > & @ . . . . . . . . . . . . . . K R.p.0.9.<.9.0.7.N.N.N.u.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8. .`.%+ .",
" .%+`. .4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.Z w w w w w w w x x y y z A P X Z  .@.#.&.-.>.).]./.1.5.a.e.i.o.s.u.w.y.A.I.W.W.Y.Y.Z.`.`. + + +=+;+,+{+{+{+{+{+{+,+{+{+,+{+]+,+,+,+L.E.r.&.z z z =.U @.).5.o.A.L.T.T.P.E.u.a.].>.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.].9 a.Z.Z.`.`. +'.! # , < f h c 0 4 } / ' * * - > ' ) ) > ; q 5 @ . . . . . + . + . . . . . 6.O.f.9.d.2.6.d.6.k.m.3.].s.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4. .`.%+ .",
" .%+`.Z 3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.>.#.#.#.#.#.#.#.#.E r r r r r r s s B E F F H L P S U Z *.-.>.!.]./.1.4.a.e.i.o.r.s.u.E.L.L.N.P.P.S.T.T.T.Y.;+,+,+,+,+;+N.G.w.-.Z 3.3.3.!.P Z -./.c.s.y.E.F.A.w.i.3.=.H 3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.>.o W.`. + +++X a X :.h j o m i f 0 4 } / ; & * - - - * 7 R.6.d $ . . . . + . . + . . . > R.B.6.6.j.2.6.d.0.7.[.1.e.e.a.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.Z `.%+ .",
" .%+`.Z :.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:. .U U U U U U U U F o o o o r r s s E U X Z @.#.&.-.>.!./.1.5.a.e.i.o.s.u.w.w.y.A.F.G.y.P Z :.:.:.:.).N S #.>.:.a.m.s.s.o.g.4.>.z !.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.o E Z.++++#+W.Y.;+++4.h m w v o j f 0 2 ! $ $ & & & ; ,.X.j.,.d @ . . . . . . . . . . 5 X.z.<.6.j.6.<.0.0.9.b.g.e.i.o.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.Z `.%+ .",
" .%+`.Z /././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././.%.F F F F F F F F w o r r s w w x z Z -.>.!.].u.E.N ]./././././.].U N X #.>.].4.8.8.4.:.R s !./././././././././././././././././././././././././././././././././././././././././././././././././././././././.r x #+#+#+%+=+;+=+++8.g o D E z r j c 4 { $ @ @ @ 7 X.K.f.(.~.5 . . . . . . . . . . p V.p.^.6.n.6.(.6.0.0.7.l.g.e.e./././././././././././././././././././././.Z `.%+ .",
" .%+`.Z /./././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././.].].].].].].].].].R y y y y z z ]./././././././.].B m r v y A D D z r X ]././././././././././././././././././././././././././././././././././././././././././././././././././././././././.].i E.#+%+%+=+-+,+-+#+G.z o E N L z o g 2 * + @ + q .+z.f.(.6.,.: . . . . . . . . @ ..O.d.^.6.n.0.(.<.6.9.6.b.h.e.e.:././././././././././././././././././././.Z `.%+ .",
" .%+`.Z ].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].;.%.%.%.%.%.%.%.*.].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].].@.9 L.=+=+-+;+;+,+=+%+W.#.o A N N z o c [ = . . ` X.p.d.<.6.0.,.! . . . . . . . % ~.J.2.~.0.n.d.(.^.2.7.6.7.l.e.e.4.].].].].].].].].].].].].].].].].].].].].Z `.%+ .",
" .%+`.Z !.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.@.L %+;+;+;+;+;+,+=+%+++4.s s E F w i 8 ! $ @ ~.V.f.0.2.6.f.6.G - . . . . . . > n.v.^.~.d.n.d.(.^.t.l.k.b.l.g.e.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.Z `.%+ .",
" .%+`.Z '.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.v #.=+;+;+;+;+;+,+=+=+%+I.L i r r k b [ ' : K.O.9.d.6.6.d.0.6.e @ . . . . ^ O R.j.~.~.d.n.f.(.}.s.r.o.m.i.e.3.>.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.Z `.%+ .",
" .%+`.Z >.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.g Z ;+;+;+;+;+;+{+=+=+=+#+&.h b c a 1 { d X.B.<.d.0.<.6.0.0.~.: . . * g r.M.V.2.,.k.q.n.j.(.b.s.r.o.o.4.!.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.Z `.%+ .",
" .%+`.Z ;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.-.h W.;+;+;+;+;+,+,+=+=+=+T.u.].j | / ~ q X.z.<.f.d.<.6.0.0.9.` : f g.L.L.U.K.~.|.y.t.v.j.(.l.s.s.8.).@.x ;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.Z `.%+ .",
" .%+`.Z -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.N c W.;+;+;+;+;+,+,+;+-+-+-+=+`.A.s | C X.q.(.j.f.2.<.9.9.9.6.}.I.P.u.w.U.v.}.y.y.A.C.p.2.t.a.'.X j [ B -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.Z `.%+ .",
" .%+`.Z *.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.L  .;+;+;+;+;+;+{+;+;+;+;+;+,+;+++I.D.X.j.^.j.j.6.^.2.6.6.9.7.|.P.w.G.U.d.y.E.E.A.y.t.}.;.P h / { z *.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.Z `.%+ .",
" .%+`.Z &.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.j /.=+;+;+;+;+,+{+,+]+{+,+=+%+#+#+*+V.9.^.j.j.6.^.^.6.6.6.6.2.Q.N.L.H.C.I.F.y.a.].Z T c ^ , ^ A &.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.Z `.%+ .",
" .%+`.Z #.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.9 ].;+;+;+;+;+,+]+-+-+=+%+%+#+#+*+O.<.~.j.n.6.^.~.k.b.7.6.<.k.N.N.L.I.u.3.@.P E 0 ! , ~ k #.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.Z `.%+ .",
" .%+`.Z #.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.@.A Z.;+;+;+;+;+{+;+-+=+%+%+#+#+.+B.^.,.j.n.0.^._.W.W.W.Q.M.M.N.G.a.=.N B h / ' , _ k @.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.Z `.%+ .",
" .%+`.X @.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.E i Y.;+;+;+;+;+;+;+=+=+%+#+#+X.v.~.~.j.n.d.^.b.W.W.W.T.T.s.#.S A m c / ) } 9 R U @.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.X `.%+ .",
" .%+`.X  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .v ].;+;+;+;+;+=+;+=+=+%+%+#+X.j.~.x.v.n.f.^.k.L.F.u.&. .z k c _ ~ } b A T  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .X `.%+ .",
" .%+`.X Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z f a.;+;+;+;+#+-+-+=+%+%+%+V.6.b.Y.M.v.f.<.[.S F w k | } ! ] f r Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z X `.%+ .",
" .%+`.X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X R | o.;+;+;+;+`.;+=+=+T.y.J._.!.-.&.l.q._.F h 4 ~ , , i s X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X `.%+ .",
" .%+`.X V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V U z #+;+;+;+'.'.'.'.>.>.|.;.X N D o C u ) , / b z U V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V X `.%+ .",
" .%+`.X T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T r r  +;+;+>.>.;.=.@.X D k g ] ] ! ~ 4 m F L T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T X `.%+ .",
" .%+`.X R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R j i.++A.Z H a | } [ ^ , ) [ [ r z R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R X `.%+ .",
" .%+`.X P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P w i 0 [ , , , , ] ] g o P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P X `.%+ .",
" .%+`.X N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N 4 , , , ^ g g N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N X `.%+ .",
" .%+`.X N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N L L L N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N X `.%+ .",
" .%+`.%.X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X %.`.%+ .",
" .%+;+`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.;+%+ .",
" .Y.%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+%+Y. .",
"N  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .N "};
